### ISSUE TITLE
Определить возможности Milestone SDK: управление камерой 

### ISSUE THREAD

**Issue by ghost** [Svinoed/IntellectEye#12]

**Comment by necheyhin-a-v** [comment]
Также необходимо узнать о возможностях получения данных записанных на сервер milestone

**Comment by ghost** [comment]
Присутствует возможность управления камерой вверх, вниз, влево и вправо.

**Comment by hases1** [comment]
управление зумом?

**Comment by ghost** [comment]
И управление зумом тоже есть. Пример находится в проекте PTZandPresets.
