### ISSUE TITLE
Посмотреть логотип команды и написать замечания и пожелания :)

### ISSUE THREAD

**Issue by ghost** [Svinoed/IntellectEye#15]
Логотип команды находится в папке "Контакты и данные".

**Comment by hases1** [comment]
[как вариант подумать о возможности совмещения с рисунком что то из этой темы](http://ruinformer.com/uploads/_pages/27709/cdf28c95656227dff417efd16f6a193d.jpg)

**Comment by katarin-gold** [comment]
Кинула свой вариант на гугл диск. Просто набросок.

**Comment by necheyhin-a-v** [comment]
Спасибо большое Сергею за цифровой вариант
