### ISSUE TITLE
Проголосовать кто каким git - клиентом хочет пользоваться 

### ISSUE THREAD

**Issue by ghost** [Svinoed/IntellectEye#16]
В итоге будет один клиент для всей команды. Это нужно сделать для того чтобы в случае возникновения трудностей один другому мог помочь. ссылка на список клиентов ниже:
https://git-scm.com/download/gui/windows

**Comment by necheyhin-a-v** [comment]
По дизайну мне понравился Кракен, но я использую GitHub desktop и изучать что-то новое во время проекта нет желания

**Comment by katarin-gold** [comment]
У меня тоже GitHub desktop, но раньше никогда его не использовала, так что могу изучить любой, положусь на ваш выбор.

**Comment by 18-th** [comment]
У меня тоже графический клиент GitHub,он вполне удобный, я за него

**Comment by hases1** [comment]
Нет задачи пользоваться всем одним клиентом, пользуйтесь чем удобно. 
Главное репозиторий не убейте
