### ISSUE TITLE
Предлагаю, поставить новую задачу: завернуть один  проектов из документации в ActiveX

### ISSUE THREAD

**Issue by ghost** [Svinoed/IntellectEye#17]

**Comment by hases1** [comment]
я предлагать правильно сформулировать название задача. *(моя твоя не понимать)

**Comment by ghost** [comment]
В документации SDK есть пример простого приложение для просмотра видео, но оно оформлено как обычное Windows-приложение. Предлагаю его попробовать переделать на ActiveX компонент. Как вы считаете стоит ли это делать ?
