### ISSUE TITLE
Выбор метода интеграции приложения с milestone

### ISSUE THREAD

**Issue by necheyhin-a-v** [Svinoed/IntellectEye#6]
Какая технология интеграции будет использоваться в дальнейшем?
- Компонентная
    использование windows, упрощенная, библиотека .NET
- Протокольная
    универсальная, работает через SOAP, поддержка на любой системе
- Plug-in
    не рассматривается в связи с ТЗ

**Comment by Svinoed** [comment]
Компонентная
использование windows, упрощенная, библиотека .NET
