### ISSUE TITLE
Система авторизации

### ISSUE THREAD

**Issue by necheyhin-a-v** [Svinoed/IntellectEye#7]
Каким образом будет производиться авторизация к серверу milestone?
Будет ли это двойная авторизация (сервер XProtect + собственная система для контроля и управления правами пользователей) либо будет все-таки только одиночная серверная авторизация на стороне XProtect?

**Comment by hases1** [comment]
Двойная авторизация.
В настройках нашего приложения задаем максимальный уровень доступа к серверу Milestone. 
Дальнейшие разграничения по уровням доступа реализуем с нашей стороны средствами Scada Infinity
